In [2]:
print("hello world")

hello world


In [5]:
%pip install numpy


  Using cached numpy-2.4.0-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Using cached numpy-2.4.0-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

# Initialize array
array_test = np.array([])

In [7]:
// n dimensional array
type(array_test)

numpy.ndarray

In [8]:
# number 
array_num = np.array([4,2,6])
print(array_num)

[4 2 6]


In [9]:
# array(range(a,b)) => from a to less than b
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
# arange(a,b)
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [180]:
# array of zeroes
np.zeros(10)
np.zeros(shape = 10)
np.zeros((3,3))
# response 0., it is shorthand for 0.0 (float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
# response 0 is zero
np.zeros(5, dtype="int")

array([0, 0, 0, 0, 0])

In [16]:
# resposnse is float
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones(4, dtype="int")

array([1, 1, 1, 1])

In [22]:
# linespace => The np.linspace() function lets you create an array containing as many elements as you’d like between a start and a stop point. 
# Note that the stop is inclusive in this case:

# always includes float start, float end divided into num equal parts
np.linspace(start=2,stop=5,num=5)

# (end-start)/(num-1)



array([2.  , 2.75, 3.5 , 4.25, 5.  ])

In [24]:
#n d array => array of arrays
np.array([[1,2,3],[4,5,6],[1,2,3]])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [34]:
# np can have mix of elements
test = np.array(["abwwwwc",1,"erf"])
test

array(['abwwwwc', '1', 'erf'], dtype='<U21')

In [35]:
type(test)

numpy.ndarray

In [36]:
# NumPy arrays are homogeneous
test.dtype
When you add the integer 1 into the mix: test = np.array(["abwwwwc", 1, "erf"]).

#NumPy sees a Mixed Type situation. On many systems (especially with modern Python and NumPy 2.0+),
#NumPy stops trying to find the "perfect fit" and instead falls back to a default buffer size
# U in incode means string

dtype('<U21')

In [31]:
test = np.array([1,1,4])
test.dtype

dtype('int64')

In [33]:
test = np.array(["abc","fghjkl","erf"])
test.dtype

dtype('<U6')

In [39]:
test = np.array(["abwwwwc",1,True])
test.dtype

dtype('<U21')

In [40]:
test = np.array([1,1.2,4])
# NumPy always promotes data to the "most complex" type present in the input.An Integer can be turned into a Float without 
# losing value ($1$ becomes $1.0$).
# A Float cannot be turned into an Integer without losing the decimal ($1.2$ would become $1$, losing the $.2$).

test.dtype

dtype('float64')

In [41]:
test = np.array([True,True])
test.dtype

dtype('bool')

In [42]:
# the Boolean type is actually a "sub-type" of integers:

# True is treated as 1.
# False is treated as 0.

test = np.array([True,12])
test.dtype

dtype('int64')

In [43]:
# the Boolean type is actually a "sub-type" of integers:

# True is treated as 1.
# False is treated as 0.


test = np.array([True,12.2])
test.dtype

dtype('float64')

In [45]:
# ******IMPORTANT*********
# Int and Float => type changes to float
# Int and boolean => type in int as boolean is also considered int
# Int and string => defaults to U21
# String => U(max length of string)
# Float and boolean => float
# Float and string => U32
# bool and string => 4/5 letter string, n letter string => U(max(n,4)


# A 64-bit float can have many decimal places, an "e" for scientific notation (like 1.2e+10), and a decimal point.

# To ensure no precision is lost when a float is turned into text, NumPy allocates a larger default buffer—usually 32 characters.

test = np.array(["fdf",12.2])
test.dtype


dtype('<U32')

In [46]:
test = np.array(["fdf",12546652])
test.dtype


dtype('<U21')

In [49]:
test = np.array([True,"sdfsd"])
test.dtype


dtype('<U5')

In [51]:
test = np.array([23,15.6,"sdfsd"])
test.dtype

dtype('<U32')

In [55]:
# ******IMPORTANT*********
# dtype of nd array is always data type
test = np.array([[123],[54,67]])
test.dtype

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [56]:
type(test)

numpy.ndarray

In [57]:

# Further features
test_array = [3,6,2,8,34,65,13,98]
test_numpy = np.array(test_array)

type(test_numpy)

numpy.ndarray

In [58]:
test_array>=18

TypeError: '>=' not supported between instances of 'list' and 'int'

In [59]:
# You can just write a expression using numpy array's name and it does the operation on every element of array

test_numpy >= 18

array([False, False, False, False,  True,  True, False,  True])

In [63]:
# To get specific index of elements
test_numpy[[3,1,4]] 
test_numpy[[2]]

# for 1D array you cannot have mutiple array to get index 
# test_numpy[[3,1,4],[[2,1,0]]] 

array([2])

In [68]:
# An array must be a perfect rectangle. In your code, the first row has 7 numbers, but the second row only has 5 numbers.
test_numpy_2D = np.array([[4,2,7,45,13,68,98],[34,21,67,87,77]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [74]:
# Fancy indexing
test_numpy_2D = np.array([[4,2,7,45,98],[34,21,67,87,77]])
# below if you see we can pickup elements using fancy indexing, but need to remember, first array is row seconf is column
# (1,2) (1,1) (0,0)
test_numpy_2D[[1,1,0],[2,1,0]] 

array([67, 21,  4])

In [75]:
# np.where always returns a Tuple,
# np.where returns index
np.where(test_numpy%2 == 0)

(array([1, 2, 3, 4, 7]),)

In [76]:
# In a 1D array, you only need one list of indices to find the values.

# In a 2D array, you need two lists (one for Rows, one for Columns).

# In a 3D array, you need three lists.
np.where(test_numpy_2D%2==0)
#  responser is one for rows, one for column

(array([0, 0, 0, 1]), array([0, 1, 4, 0]))

In [78]:
test_numpy[4]

np.int64(34)

In [79]:
test_numpy_2D[1][2]

np.int64(67)

In [80]:
# Fancy indexing follows the shape of the index list you provide.
arr = np.array([10, 20, 30, 40])
indices = np.array([[0, 1], 
                    [2, 3]])

print(arr[indices])



[[10 20]
 [30 40]]


In [ ]:
# **********IMPORTANT***********
# Normal indexing, will lead to pointing address to the new variable where as in fancy, a clone is created.

In [81]:
test_numpy_2D[test_numpy_2D>20]

array([45, 98, 34, 21, 67, 87, 77])

In [ ]:
"""
3D array, return value if true condition, else return some other value3
np.where(condition, if true what to do, else what to do)


use of :

use of ...
"""

In [ ]:
"""
Np array manipulation

1. append: 1d, 2d(axis)
2. delete
3. concatenate

"""

In [82]:
array = np.array([2,4,5,7,8])
np.append(arr,4)

array([10, 20, 30, 40,  4])

In [84]:
array1 = np.array([2,4,5,7,8])
array2 = np.array([12,42,35,75,8])
array3 = np.array([2,24,55,7,8])
np.concatenate([array1, array2, array3])

array([ 2,  4,  5,  7,  8, 12, 42, 35, 75,  8,  2, 24, 55,  7,  8])

In [85]:
array1 = np.array([2,4,5,7,8])
array2 = np.array([12,42,35,75,8])
np.append(array1,array2)

array([ 2,  4,  5,  7,  8, 12, 42, 35, 75,  8])

In [ ]:
"""
The Axis Rules (for 2D)
axis = 0: Operates downward (along the rows).

axis = 1: Operates sideways (along the columns).
"""


In [95]:
array1 = np.array([[2,4,45],[5,7,8]])
array2 = np.array([[12,42,35],[75,8,1]])

In [96]:
np.concatenate((array1,array2),axis = 0) # add to row(more rows)

array([[ 2,  4, 45],
       [ 5,  7,  8],
       [12, 42, 35],
       [75,  8,  1]])

In [93]:
array1 = np.array([[2,4,4],[5,7,8]])
array2 = np.array([[12,42,35],[75,8,6]])

In [94]:
np.concatenate((array1,array2),axis = 1) # add to columns(more columns)

array([[ 2,  4,  4, 12, 42, 35],
       [ 5,  7,  8, 75,  8,  6]])

In [ ]:
"""
reshape => Reshaping changes the "shape" (dimensions) of an array. The only rule is that the total number .
of elements must remain the same. Eg: Rearranging 12 eggs from a $6 \times 2$ carton into a $4 \times 3$ carton.

transpose 1D, 2D, 3D=> Transposing flips an array over its diagonal. It switches the axes. This is the most common use. 
Rows become columns, and columns become rows.
In 3D, you have axes (0, 1, 2) representing (Depth, Height, Width). Transposing allows you to swap any of these.

flatten


.append() in 2D needs to have same number of rows
"""

In [99]:
# Reshape:
array = np.array([4,6,3,7,8,9])
np.reshape(array,(2,3))
np.reshape(array,(1,6))


array([[4, 6, 3, 7, 8, 9]])

In [101]:
np.reshape(array,(1,2,3))

array([[[4, 6, 3],
        [7, 8, 9]]])

In [102]:
np.reshape(array,(3,1,2))

array([[[4, 6]],

       [[3, 7]],

       [[8, 9]]])

In [103]:
# transpose
mat = np.array([[3,5,7],[2,1,7]])
mat.transpose()
mat.T
            

array([[3, 2],
       [5, 1],
       [7, 7]])

In [104]:
# flatten
mat = np.array([[3,5,7],[2,1,7]])
mat.flatten()

array([3, 5, 7, 2, 1, 7])

In [ ]:
"""
broadcasting: Broadcasting in NumPy is a powerful feature that allows arithmetic operations on arrays of different 
shapes by virtually stretching or "broadcasting" the smaller array to match the larger one's shape

list comprehension
"""

In [105]:
test = np.array([[1,2,4],[6,4,9],[5,2,4]])
test

array([[1, 2, 4],
       [6, 4, 9],
       [5, 2, 4]])

In [106]:
test + np.array([1,2,3])

array([[ 2,  4,  7],
       [ 7,  6, 12],
       [ 6,  4,  7]])

In [107]:
test = np.array([[1,2,4],[6,4,9],[5,2,4]])
test

array([[1, 2, 4],
       [6, 4, 9],
       [5, 2, 4]])

In [108]:
test * np.array([1,2,3])

array([[ 1,  4, 12],
       [ 6,  8, 27],
       [ 5,  4, 12]])

In [ ]:
"""
Dot poduct mat1 @ mat2v => matrix multiplication => rows*columns

.sum()

.sum(axis``

"""

In [109]:
""" 
shape => no of rows and no of columns
"""
test = np.array([[1,2,4],[6,4,9],[5,2,4]])
test.shape


(3, 3)

In [110]:
test[1:3,1:3]

array([[4, 9],
       [2, 4]])

In [ ]:
"""
np.eye()
np.diag() => diagonal matrix
np.subtract
"""

In [112]:
"""
apply() in pandas
"""
%pip install pandas


  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 4.1 MB/s  0:00:024.2 MB/s eta 0:00:0102
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]━━━━ 1/2 [pandas]
Note: you may need to restart the kernel to use updated packages.


In [113]:
import pandas as pd

In [116]:
ser1 = pd.Series()
type(ser1)

pandas.core.series.Series

In [118]:
ser1.dtype

dtype('O')

In [119]:
ser1.ndim

1

In [120]:
ser1.name

In [121]:
ser1.shape

(0,)

In [122]:
ser1.size

0

In [123]:
ser2 = pd.Series([1,2,3,4])

In [124]:
ser2

0    1
1    2
2    3
3    4
dtype: int64

In [125]:
ser2 = pd.Series([2,"hat", True])
ser2

0       2
1     hat
2    True
dtype: object

In [126]:
ser2.values

array([2, 'hat', True], dtype=object)

In [127]:
print(ser2.size)
# Object when type is mixed
print(ser2.dtype)
print(ser2.shape)

3
object
(3,)


In [129]:
ser2 = pd.Series({'A':1,'B':2,'C':3,'D':4})
ser2

A    1
B    2
C    3
D    4
dtype: int64

In [130]:
ser2.index

Index(['A', 'B', 'C', 'D'], dtype='object')

ser2.dtype

In [131]:
ser2.dtype

dtype('int64')

In [132]:
ser2.shape

(4,)

In [133]:
# Anothefr way of declaring pandas
ser2 = pd.Series([1,2],[3,4])
ser2

3    1
4    2
dtype: int64

In [136]:
ser2 = pd.Series([[1,2],[3,4]])
ser2
ser2.shape

(2,)

In [138]:
ser2 = pd.Series([[[1,2],[2,4]],[3,4]])
ser2

0    [[1, 2], [2, 4]]
1              [3, 4]
dtype: object

In [140]:
matrix_data = [[10, 20], [30, 40]]
ser = pd.Series([matrix_data])

ser

0    [[10, 20], [30, 40]]
dtype: object

In [143]:
ser2 = pd.Series({'A':1,'B':2,'C':3,'D':4})

# iloc : original index by default
# loc : used to fetch using defined labels

ser2.iloc[2]

np.int64(3)

In [144]:
ser2.iloc[2].dtype

dtype('int64')

In [146]:
# ser2.loc[2]  will not work
ser2.loc['A']
# ser2['A'] will also work

np.int64(1)

In [147]:
# slicing
ser2.iloc[0:2]


A    1
B    2
dtype: int64

In [148]:
ser2.loc['A':'C'] 
# start end both are inclusive, can give step also

A    1
B    2
C    3
dtype: int64

In [150]:
ser2 = pd.Series({'A':31,'B':25,'C':13,'D':24})
sorted_series = ser2.sort_values() #ascending my default
sorted_series

C    13
D    24
B    25
A    31
dtype: int64

In [151]:
ser2 = pd.Series({'A':31,'B':25,'C':13,'D':24})
sorted_series = ser2.sort_index() #ascending my default
sorted_series

A    31
B    25
C    13
D    24
dtype: int64

In [152]:
ser2 = pd.Series({'A':31,'B':25,'C':13,'D':24})
ser2.loc[ser2.isin([3,25])]

B    25
dtype: int64

In [153]:
# not in
ser2.loc[~ser2.isin([3,25])]

A    31
C    13
D    24
dtype: int64

In [155]:
ser2.loc[ser2 >= 30]

A    31
dtype: int64

In [157]:
ser2.iloc[[1,1,0]]

B    25
B    25
A    31
dtype: int64

In [158]:
ser2.loc[['A','B','B']]

A    31
B    25
B    25
dtype: int64

In [163]:
# second is indices, first is values
pd1 = pd.Series([2,4,6,1], ['A','B','C','D'])
pd2 = pd.Series([62,34,31],['A','B','D'])

pd1+pd2

A    64.0
B    38.0
C     NaN
D    32.0
dtype: float64

In [164]:
pd1.add(pd2)

A    64.0
B    38.0
C     NaN
D    32.0
dtype: float64

In [165]:
# fill prefil that index with 0 before adding
pd1.add(pd2,fill_value=0)

A    64.0
B    38.0
C     6.0
D    32.0
dtype: float64

In [169]:
(pd1+pd2).fillna("Nothing to show")

A               64.0
B               38.0
C    Nothing to show
D               32.0
dtype: object

In [170]:
pdRes = pd1 + pd2
pdRes.dropna()

A    64.0
B    38.0
D    32.0
dtype: float64

In [171]:
pd1.reset_index()

index  0
0     A  2
1     B  4
2     C  6
3     D  1

In [173]:
pd3 = pd2.mean()
pd3

np.float64(42.333333333333336)

In [174]:
pd2.index.isin(["aa","D"])

# shift(1) => move righgt
# shift(-1) => move left

array([False, False,  True])

In [175]:
"""
inplace = true is for modifying original data strcutue
.head(), which will reveal the top n elements of the series 
.tail() which will reveal the bottom n elements of the series
.describe() can be used to retrieve some summary statistics of the series
remove duplicates in a series by using the .drop_duplicates()
identify duplicates by using the .duplicated
apply functions on every element of a series using .apply() or .map()
"""

_IncompleteInputError: incomplete input (221781945.py, line 1)

In [178]:
pdTest= pd.Series([3,24,67,87,12])
pdtestSq = pdTest.apply(lambda x : x**2)
pdtestSq


0       9
1     576
2    4489
3    7569
4     144
dtype: int64

In [184]:
numpuArr = np.array([2,5,3,6,8,6])
numArr = numpuArr.reshape(2,3)
numArr

array([[2, 5, 3],
       [6, 8, 6]])

In [185]:
numArr.transpose()

array([[2, 6],
       [5, 8],
       [3, 6]])